kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-viewer
  annotations:
    openshift.io/description: Allows viewing details related to builds
rules:

  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - build.openshift.io
    resources:
      - buildconfigs
      - buildconfigs/webhooks
      - builds
      - builds/details
      - builds/log
      - buildlogs
  - verbs:
      - view
    apiGroups:
      - build.openshift.io
    resources:
      - jenkins
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - image.openshift.io
    resources:
      - imagestreamimages
      - imagestreammappings
      - imagestreams
      - imagestreams/layers
      - imagestreams/status
      - imagestreamtags
      - imagetags
      - imagestreamimports
