kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-logging-user
  annotations:
    openshift.io/description: Allows administration of namespaced Elasticsearch clusters (for app log aggregation)
rules:
  - verbs:
      - '*'
    apiGroups:
      - logging.openshift.io
    resources:
      - elasticsearches
      - kibanas
      - logforwardings
