kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: top-runner
  annotations:
    openshift.io/description: Allows the use of `kubectl top` commands to view statistics
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
